/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthLoginRouteRouteImport } from './routes/_auth/login/route'
import { Route as AppPeopleRouteRouteImport } from './routes/_app/people/route'
import { Route as AppOverviewRouteRouteImport } from './routes/_app/overview/route'
import { Route as AppAttendanceRouteRouteImport } from './routes/_app/attendance/route'
import { Route as AppPeopleIdRouteRouteImport } from './routes/_app/people/$id/route'
import { Route as AppAttendanceMonthlyRouteRouteImport } from './routes/_app/attendance/monthly/route'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRouteRoute = AuthLoginRouteRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AppPeopleRouteRoute = AppPeopleRouteRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOverviewRouteRoute = AppOverviewRouteRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAttendanceRouteRoute = AppAttendanceRouteRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPeopleIdRouteRoute = AppPeopleIdRouteRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppPeopleRouteRoute,
} as any)
const AppAttendanceMonthlyRouteRoute =
  AppAttendanceMonthlyRouteRouteImport.update({
    id: '/monthly',
    path: '/monthly',
    getParentRoute: () => AppAttendanceRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/attendance': typeof AppAttendanceRouteRouteWithChildren
  '/overview': typeof AppOverviewRouteRoute
  '/people': typeof AppPeopleRouteRouteWithChildren
  '/login': typeof AuthLoginRouteRoute
  '/attendance/monthly': typeof AppAttendanceMonthlyRouteRoute
  '/people/$id': typeof AppPeopleIdRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/attendance': typeof AppAttendanceRouteRouteWithChildren
  '/overview': typeof AppOverviewRouteRoute
  '/people': typeof AppPeopleRouteRouteWithChildren
  '/login': typeof AuthLoginRouteRoute
  '/attendance/monthly': typeof AppAttendanceMonthlyRouteRoute
  '/people/$id': typeof AppPeopleIdRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_app/attendance': typeof AppAttendanceRouteRouteWithChildren
  '/_app/overview': typeof AppOverviewRouteRoute
  '/_app/people': typeof AppPeopleRouteRouteWithChildren
  '/_auth/login': typeof AuthLoginRouteRoute
  '/_app/attendance/monthly': typeof AppAttendanceMonthlyRouteRoute
  '/_app/people/$id': typeof AppPeopleIdRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/attendance'
    | '/overview'
    | '/people'
    | '/login'
    | '/attendance/monthly'
    | '/people/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/attendance'
    | '/overview'
    | '/people'
    | '/login'
    | '/attendance/monthly'
    | '/people/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/_app/attendance'
    | '/_app/overview'
    | '/_app/people'
    | '/_auth/login'
    | '/_app/attendance/monthly'
    | '/_app/people/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_app/people': {
      id: '/_app/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof AppPeopleRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/overview': {
      id: '/_app/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof AppOverviewRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/attendance': {
      id: '/_app/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AppAttendanceRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/people/$id': {
      id: '/_app/people/$id'
      path: '/$id'
      fullPath: '/people/$id'
      preLoaderRoute: typeof AppPeopleIdRouteRouteImport
      parentRoute: typeof AppPeopleRouteRoute
    }
    '/_app/attendance/monthly': {
      id: '/_app/attendance/monthly'
      path: '/monthly'
      fullPath: '/attendance/monthly'
      preLoaderRoute: typeof AppAttendanceMonthlyRouteRouteImport
      parentRoute: typeof AppAttendanceRouteRoute
    }
  }
}

interface AppAttendanceRouteRouteChildren {
  AppAttendanceMonthlyRouteRoute: typeof AppAttendanceMonthlyRouteRoute
}

const AppAttendanceRouteRouteChildren: AppAttendanceRouteRouteChildren = {
  AppAttendanceMonthlyRouteRoute: AppAttendanceMonthlyRouteRoute,
}

const AppAttendanceRouteRouteWithChildren =
  AppAttendanceRouteRoute._addFileChildren(AppAttendanceRouteRouteChildren)

interface AppPeopleRouteRouteChildren {
  AppPeopleIdRouteRoute: typeof AppPeopleIdRouteRoute
}

const AppPeopleRouteRouteChildren: AppPeopleRouteRouteChildren = {
  AppPeopleIdRouteRoute: AppPeopleIdRouteRoute,
}

const AppPeopleRouteRouteWithChildren = AppPeopleRouteRoute._addFileChildren(
  AppPeopleRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppAttendanceRouteRoute: typeof AppAttendanceRouteRouteWithChildren
  AppOverviewRouteRoute: typeof AppOverviewRouteRoute
  AppPeopleRouteRoute: typeof AppPeopleRouteRouteWithChildren
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAttendanceRouteRoute: AppAttendanceRouteRouteWithChildren,
  AppOverviewRouteRoute: AppOverviewRouteRoute,
  AppPeopleRouteRoute: AppPeopleRouteRouteWithChildren,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthLoginRouteRoute: typeof AuthLoginRouteRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRouteRoute: AuthLoginRouteRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
