/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSetupOrgRouteRouteImport } from './routes/_auth/setup-org/route'
import { Route as AuthRegisterRouteRouteImport } from './routes/_auth/register/route'
import { Route as AuthLoginRouteRouteImport } from './routes/_auth/login/route'
import { Route as AuthInviteRouteRouteImport } from './routes/_auth/invite/route'
import { Route as AppTasksRouteRouteImport } from './routes/_app/tasks/route'
import { Route as AppSettingsRouteRouteImport } from './routes/_app/settings/route'
import { Route as AppReportsRouteRouteImport } from './routes/_app/reports/route'
import { Route as AppPeopleRouteRouteImport } from './routes/_app/people/route'
import { Route as AppOverviewRouteRouteImport } from './routes/_app/overview/route'
import { Route as AppFeatureDisabledRouteRouteImport } from './routes/_app/feature-disabled/route'
import { Route as AppAttendanceRouteRouteImport } from './routes/_app/attendance/route'
import { Route as AppAdminRouteRouteImport } from './routes/_app/admin/route'
import { Route as AppPeopleIndexRouteImport } from './routes/_app/people/index'
import { Route as AppAttendanceIndexRouteImport } from './routes/_app/attendance/index'
import { Route as AppAdminIndexRouteImport } from './routes/_app/admin/index'
import { Route as AppAdminLicensesRouteImport } from './routes/_app/admin/licenses'
import { Route as AppAdminFeaturesRouteImport } from './routes/_app/admin/features'
import { Route as AppAdminConfigRouteImport } from './routes/_app/admin/config'
import { Route as AppSettingsMembersRouteRouteImport } from './routes/_app/settings/members/route'
import { Route as AppSettingsCompanyRouteRouteImport } from './routes/_app/settings/company/route'
import { Route as AppPeopleIdRouteRouteImport } from './routes/_app/people/$id/route'
import { Route as AppAttendanceMonthlyRouteRouteImport } from './routes/_app/attendance/monthly/route'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSetupOrgRouteRoute = AuthSetupOrgRouteRouteImport.update({
  id: '/setup-org',
  path: '/setup-org',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthRegisterRouteRoute = AuthRegisterRouteRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRouteRoute = AuthLoginRouteRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthInviteRouteRoute = AuthInviteRouteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AppTasksRouteRoute = AppTasksRouteRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsRouteRoute = AppSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppReportsRouteRoute = AppReportsRouteRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPeopleRouteRoute = AppPeopleRouteRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOverviewRouteRoute = AppOverviewRouteRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFeatureDisabledRouteRoute = AppFeatureDisabledRouteRouteImport.update({
  id: '/feature-disabled',
  path: '/feature-disabled',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAttendanceRouteRoute = AppAttendanceRouteRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAdminRouteRoute = AppAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPeopleIndexRoute = AppPeopleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPeopleRouteRoute,
} as any)
const AppAttendanceIndexRoute = AppAttendanceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAttendanceRouteRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRouteRoute,
} as any)
const AppAdminLicensesRoute = AppAdminLicensesRouteImport.update({
  id: '/licenses',
  path: '/licenses',
  getParentRoute: () => AppAdminRouteRoute,
} as any)
const AppAdminFeaturesRoute = AppAdminFeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => AppAdminRouteRoute,
} as any)
const AppAdminConfigRoute = AppAdminConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => AppAdminRouteRoute,
} as any)
const AppSettingsMembersRouteRoute = AppSettingsMembersRouteRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSettingsCompanyRouteRoute = AppSettingsCompanyRouteRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppPeopleIdRouteRoute = AppPeopleIdRouteRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppPeopleRouteRoute,
} as any)
const AppAttendanceMonthlyRouteRoute =
  AppAttendanceMonthlyRouteRouteImport.update({
    id: '/monthly',
    path: '/monthly',
    getParentRoute: () => AppAttendanceRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AppAdminRouteRouteWithChildren
  '/attendance': typeof AppAttendanceRouteRouteWithChildren
  '/feature-disabled': typeof AppFeatureDisabledRouteRoute
  '/overview': typeof AppOverviewRouteRoute
  '/people': typeof AppPeopleRouteRouteWithChildren
  '/reports': typeof AppReportsRouteRoute
  '/settings': typeof AppSettingsRouteRouteWithChildren
  '/tasks': typeof AppTasksRouteRoute
  '/invite': typeof AuthInviteRouteRoute
  '/login': typeof AuthLoginRouteRoute
  '/register': typeof AuthRegisterRouteRoute
  '/setup-org': typeof AuthSetupOrgRouteRoute
  '/attendance/monthly': typeof AppAttendanceMonthlyRouteRoute
  '/people/$id': typeof AppPeopleIdRouteRoute
  '/settings/company': typeof AppSettingsCompanyRouteRoute
  '/settings/members': typeof AppSettingsMembersRouteRoute
  '/admin/config': typeof AppAdminConfigRoute
  '/admin/features': typeof AppAdminFeaturesRoute
  '/admin/licenses': typeof AppAdminLicensesRoute
  '/admin/': typeof AppAdminIndexRoute
  '/attendance/': typeof AppAttendanceIndexRoute
  '/people/': typeof AppPeopleIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/feature-disabled': typeof AppFeatureDisabledRouteRoute
  '/overview': typeof AppOverviewRouteRoute
  '/reports': typeof AppReportsRouteRoute
  '/settings': typeof AppSettingsRouteRouteWithChildren
  '/tasks': typeof AppTasksRouteRoute
  '/invite': typeof AuthInviteRouteRoute
  '/login': typeof AuthLoginRouteRoute
  '/register': typeof AuthRegisterRouteRoute
  '/setup-org': typeof AuthSetupOrgRouteRoute
  '/attendance/monthly': typeof AppAttendanceMonthlyRouteRoute
  '/people/$id': typeof AppPeopleIdRouteRoute
  '/settings/company': typeof AppSettingsCompanyRouteRoute
  '/settings/members': typeof AppSettingsMembersRouteRoute
  '/admin/config': typeof AppAdminConfigRoute
  '/admin/features': typeof AppAdminFeaturesRoute
  '/admin/licenses': typeof AppAdminLicensesRoute
  '/admin': typeof AppAdminIndexRoute
  '/attendance': typeof AppAttendanceIndexRoute
  '/people': typeof AppPeopleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_app/admin': typeof AppAdminRouteRouteWithChildren
  '/_app/attendance': typeof AppAttendanceRouteRouteWithChildren
  '/_app/feature-disabled': typeof AppFeatureDisabledRouteRoute
  '/_app/overview': typeof AppOverviewRouteRoute
  '/_app/people': typeof AppPeopleRouteRouteWithChildren
  '/_app/reports': typeof AppReportsRouteRoute
  '/_app/settings': typeof AppSettingsRouteRouteWithChildren
  '/_app/tasks': typeof AppTasksRouteRoute
  '/_auth/invite': typeof AuthInviteRouteRoute
  '/_auth/login': typeof AuthLoginRouteRoute
  '/_auth/register': typeof AuthRegisterRouteRoute
  '/_auth/setup-org': typeof AuthSetupOrgRouteRoute
  '/_app/attendance/monthly': typeof AppAttendanceMonthlyRouteRoute
  '/_app/people/$id': typeof AppPeopleIdRouteRoute
  '/_app/settings/company': typeof AppSettingsCompanyRouteRoute
  '/_app/settings/members': typeof AppSettingsMembersRouteRoute
  '/_app/admin/config': typeof AppAdminConfigRoute
  '/_app/admin/features': typeof AppAdminFeaturesRoute
  '/_app/admin/licenses': typeof AppAdminLicensesRoute
  '/_app/admin/': typeof AppAdminIndexRoute
  '/_app/attendance/': typeof AppAttendanceIndexRoute
  '/_app/people/': typeof AppPeopleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/attendance'
    | '/feature-disabled'
    | '/overview'
    | '/people'
    | '/reports'
    | '/settings'
    | '/tasks'
    | '/invite'
    | '/login'
    | '/register'
    | '/setup-org'
    | '/attendance/monthly'
    | '/people/$id'
    | '/settings/company'
    | '/settings/members'
    | '/admin/config'
    | '/admin/features'
    | '/admin/licenses'
    | '/admin/'
    | '/attendance/'
    | '/people/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/feature-disabled'
    | '/overview'
    | '/reports'
    | '/settings'
    | '/tasks'
    | '/invite'
    | '/login'
    | '/register'
    | '/setup-org'
    | '/attendance/monthly'
    | '/people/$id'
    | '/settings/company'
    | '/settings/members'
    | '/admin/config'
    | '/admin/features'
    | '/admin/licenses'
    | '/admin'
    | '/attendance'
    | '/people'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/_app/admin'
    | '/_app/attendance'
    | '/_app/feature-disabled'
    | '/_app/overview'
    | '/_app/people'
    | '/_app/reports'
    | '/_app/settings'
    | '/_app/tasks'
    | '/_auth/invite'
    | '/_auth/login'
    | '/_auth/register'
    | '/_auth/setup-org'
    | '/_app/attendance/monthly'
    | '/_app/people/$id'
    | '/_app/settings/company'
    | '/_app/settings/members'
    | '/_app/admin/config'
    | '/_app/admin/features'
    | '/_app/admin/licenses'
    | '/_app/admin/'
    | '/_app/attendance/'
    | '/_app/people/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/setup-org': {
      id: '/_auth/setup-org'
      path: '/setup-org'
      fullPath: '/setup-org'
      preLoaderRoute: typeof AuthSetupOrgRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/invite': {
      id: '/_auth/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof AuthInviteRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_app/tasks': {
      id: '/_app/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AppTasksRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/people': {
      id: '/_app/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof AppPeopleRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/overview': {
      id: '/_app/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof AppOverviewRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/feature-disabled': {
      id: '/_app/feature-disabled'
      path: '/feature-disabled'
      fullPath: '/feature-disabled'
      preLoaderRoute: typeof AppFeatureDisabledRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/attendance': {
      id: '/_app/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AppAttendanceRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/people/': {
      id: '/_app/people/'
      path: '/'
      fullPath: '/people/'
      preLoaderRoute: typeof AppPeopleIndexRouteImport
      parentRoute: typeof AppPeopleRouteRoute
    }
    '/_app/attendance/': {
      id: '/_app/attendance/'
      path: '/'
      fullPath: '/attendance/'
      preLoaderRoute: typeof AppAttendanceIndexRouteImport
      parentRoute: typeof AppAttendanceRouteRoute
    }
    '/_app/admin/': {
      id: '/_app/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/_app/admin/licenses': {
      id: '/_app/admin/licenses'
      path: '/licenses'
      fullPath: '/admin/licenses'
      preLoaderRoute: typeof AppAdminLicensesRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/_app/admin/features': {
      id: '/_app/admin/features'
      path: '/features'
      fullPath: '/admin/features'
      preLoaderRoute: typeof AppAdminFeaturesRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/_app/admin/config': {
      id: '/_app/admin/config'
      path: '/config'
      fullPath: '/admin/config'
      preLoaderRoute: typeof AppAdminConfigRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/_app/settings/members': {
      id: '/_app/settings/members'
      path: '/members'
      fullPath: '/settings/members'
      preLoaderRoute: typeof AppSettingsMembersRouteRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/settings/company': {
      id: '/_app/settings/company'
      path: '/company'
      fullPath: '/settings/company'
      preLoaderRoute: typeof AppSettingsCompanyRouteRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/people/$id': {
      id: '/_app/people/$id'
      path: '/$id'
      fullPath: '/people/$id'
      preLoaderRoute: typeof AppPeopleIdRouteRouteImport
      parentRoute: typeof AppPeopleRouteRoute
    }
    '/_app/attendance/monthly': {
      id: '/_app/attendance/monthly'
      path: '/monthly'
      fullPath: '/attendance/monthly'
      preLoaderRoute: typeof AppAttendanceMonthlyRouteRouteImport
      parentRoute: typeof AppAttendanceRouteRoute
    }
  }
}

interface AppAdminRouteRouteChildren {
  AppAdminConfigRoute: typeof AppAdminConfigRoute
  AppAdminFeaturesRoute: typeof AppAdminFeaturesRoute
  AppAdminLicensesRoute: typeof AppAdminLicensesRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
}

const AppAdminRouteRouteChildren: AppAdminRouteRouteChildren = {
  AppAdminConfigRoute: AppAdminConfigRoute,
  AppAdminFeaturesRoute: AppAdminFeaturesRoute,
  AppAdminLicensesRoute: AppAdminLicensesRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
}

const AppAdminRouteRouteWithChildren = AppAdminRouteRoute._addFileChildren(
  AppAdminRouteRouteChildren,
)

interface AppAttendanceRouteRouteChildren {
  AppAttendanceMonthlyRouteRoute: typeof AppAttendanceMonthlyRouteRoute
  AppAttendanceIndexRoute: typeof AppAttendanceIndexRoute
}

const AppAttendanceRouteRouteChildren: AppAttendanceRouteRouteChildren = {
  AppAttendanceMonthlyRouteRoute: AppAttendanceMonthlyRouteRoute,
  AppAttendanceIndexRoute: AppAttendanceIndexRoute,
}

const AppAttendanceRouteRouteWithChildren =
  AppAttendanceRouteRoute._addFileChildren(AppAttendanceRouteRouteChildren)

interface AppPeopleRouteRouteChildren {
  AppPeopleIdRouteRoute: typeof AppPeopleIdRouteRoute
  AppPeopleIndexRoute: typeof AppPeopleIndexRoute
}

const AppPeopleRouteRouteChildren: AppPeopleRouteRouteChildren = {
  AppPeopleIdRouteRoute: AppPeopleIdRouteRoute,
  AppPeopleIndexRoute: AppPeopleIndexRoute,
}

const AppPeopleRouteRouteWithChildren = AppPeopleRouteRoute._addFileChildren(
  AppPeopleRouteRouteChildren,
)

interface AppSettingsRouteRouteChildren {
  AppSettingsCompanyRouteRoute: typeof AppSettingsCompanyRouteRoute
  AppSettingsMembersRouteRoute: typeof AppSettingsMembersRouteRoute
}

const AppSettingsRouteRouteChildren: AppSettingsRouteRouteChildren = {
  AppSettingsCompanyRouteRoute: AppSettingsCompanyRouteRoute,
  AppSettingsMembersRouteRoute: AppSettingsMembersRouteRoute,
}

const AppSettingsRouteRouteWithChildren =
  AppSettingsRouteRoute._addFileChildren(AppSettingsRouteRouteChildren)

interface AppRouteRouteChildren {
  AppAdminRouteRoute: typeof AppAdminRouteRouteWithChildren
  AppAttendanceRouteRoute: typeof AppAttendanceRouteRouteWithChildren
  AppFeatureDisabledRouteRoute: typeof AppFeatureDisabledRouteRoute
  AppOverviewRouteRoute: typeof AppOverviewRouteRoute
  AppPeopleRouteRoute: typeof AppPeopleRouteRouteWithChildren
  AppReportsRouteRoute: typeof AppReportsRouteRoute
  AppSettingsRouteRoute: typeof AppSettingsRouteRouteWithChildren
  AppTasksRouteRoute: typeof AppTasksRouteRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAdminRouteRoute: AppAdminRouteRouteWithChildren,
  AppAttendanceRouteRoute: AppAttendanceRouteRouteWithChildren,
  AppFeatureDisabledRouteRoute: AppFeatureDisabledRouteRoute,
  AppOverviewRouteRoute: AppOverviewRouteRoute,
  AppPeopleRouteRoute: AppPeopleRouteRouteWithChildren,
  AppReportsRouteRoute: AppReportsRouteRoute,
  AppSettingsRouteRoute: AppSettingsRouteRouteWithChildren,
  AppTasksRouteRoute: AppTasksRouteRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthInviteRouteRoute: typeof AuthInviteRouteRoute
  AuthLoginRouteRoute: typeof AuthLoginRouteRoute
  AuthRegisterRouteRoute: typeof AuthRegisterRouteRoute
  AuthSetupOrgRouteRoute: typeof AuthSetupOrgRouteRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthInviteRouteRoute: AuthInviteRouteRoute,
  AuthLoginRouteRoute: AuthLoginRouteRoute,
  AuthRegisterRouteRoute: AuthRegisterRouteRoute,
  AuthSetupOrgRouteRoute: AuthSetupOrgRouteRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
