/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSetupOrgRouteRouteImport } from './routes/_auth/setup-org/route'
import { Route as AuthRegisterRouteRouteImport } from './routes/_auth/register/route'
import { Route as AuthLoginRouteRouteImport } from './routes/_auth/login/route'
import { Route as AuthInviteRouteRouteImport } from './routes/_auth/invite/route'
import { Route as AppTasksRouteRouteImport } from './routes/_app/tasks/route'
import { Route as AppSettingsRouteRouteImport } from './routes/_app/settings/route'
import { Route as AppReportsRouteRouteImport } from './routes/_app/reports/route'
import { Route as AppPeopleRouteRouteImport } from './routes/_app/people/route'
import { Route as AppOverviewRouteRouteImport } from './routes/_app/overview/route'
import { Route as AppLeaveRouteRouteImport } from './routes/_app/leave/route'
import { Route as AppFeatureDisabledRouteRouteImport } from './routes/_app/feature-disabled/route'
import { Route as AppClaimsRouteRouteImport } from './routes/_app/claims/route'
import { Route as AppAttendanceRouteRouteImport } from './routes/_app/attendance/route'
import { Route as AppPeopleIndexRouteImport } from './routes/_app/people/index'
import { Route as AppLeaveIndexRouteImport } from './routes/_app/leave/index'
import { Route as AppClaimsIndexRouteImport } from './routes/_app/claims/index'
import { Route as AppAttendanceIndexRouteImport } from './routes/_app/attendance/index'
import { Route as AppLeaveCalendarRouteImport } from './routes/_app/leave/calendar'
import { Route as AppClaimsNewRouteImport } from './routes/_app/claims/new'
import { Route as AppSettingsMembersRouteRouteImport } from './routes/_app/settings/members/route'
import { Route as AppSettingsCompanyRouteRouteImport } from './routes/_app/settings/company/route'
import { Route as AppPeopleIdRouteRouteImport } from './routes/_app/people/$id/route'
import { Route as AppAttendanceMonthlyRouteRouteImport } from './routes/_app/attendance/monthly/route'
import { Route as AppLeaveRequestsIndexRouteImport } from './routes/_app/leave/requests/index'
import { Route as AppLeavePoliciesIndexRouteImport } from './routes/_app/leave/policies/index'
import { Route as AppLeaveRequestsPendingRouteImport } from './routes/_app/leave/requests/pending'
import { Route as AppLeaveRequestsNewRouteImport } from './routes/_app/leave/requests/new'
import { Route as AppLeavePoliciesNewRouteImport } from './routes/_app/leave/policies/new'
import { Route as AppLeavePoliciesIdRouteImport } from './routes/_app/leave/policies/$id'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSetupOrgRouteRoute = AuthSetupOrgRouteRouteImport.update({
  id: '/setup-org',
  path: '/setup-org',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthRegisterRouteRoute = AuthRegisterRouteRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRouteRoute = AuthLoginRouteRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthInviteRouteRoute = AuthInviteRouteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AppTasksRouteRoute = AppTasksRouteRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsRouteRoute = AppSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppReportsRouteRoute = AppReportsRouteRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPeopleRouteRoute = AppPeopleRouteRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOverviewRouteRoute = AppOverviewRouteRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLeaveRouteRoute = AppLeaveRouteRouteImport.update({
  id: '/leave',
  path: '/leave',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFeatureDisabledRouteRoute = AppFeatureDisabledRouteRouteImport.update({
  id: '/feature-disabled',
  path: '/feature-disabled',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppClaimsRouteRoute = AppClaimsRouteRouteImport.update({
  id: '/claims',
  path: '/claims',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAttendanceRouteRoute = AppAttendanceRouteRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPeopleIndexRoute = AppPeopleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPeopleRouteRoute,
} as any)
const AppLeaveIndexRoute = AppLeaveIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLeaveRouteRoute,
} as any)
const AppClaimsIndexRoute = AppClaimsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppClaimsRouteRoute,
} as any)
const AppAttendanceIndexRoute = AppAttendanceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAttendanceRouteRoute,
} as any)
const AppLeaveCalendarRoute = AppLeaveCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppLeaveRouteRoute,
} as any)
const AppClaimsNewRoute = AppClaimsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppClaimsRouteRoute,
} as any)
const AppSettingsMembersRouteRoute = AppSettingsMembersRouteRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSettingsCompanyRouteRoute = AppSettingsCompanyRouteRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppPeopleIdRouteRoute = AppPeopleIdRouteRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppPeopleRouteRoute,
} as any)
const AppAttendanceMonthlyRouteRoute =
  AppAttendanceMonthlyRouteRouteImport.update({
    id: '/monthly',
    path: '/monthly',
    getParentRoute: () => AppAttendanceRouteRoute,
  } as any)
const AppLeaveRequestsIndexRoute = AppLeaveRequestsIndexRouteImport.update({
  id: '/requests/',
  path: '/requests/',
  getParentRoute: () => AppLeaveRouteRoute,
} as any)
const AppLeavePoliciesIndexRoute = AppLeavePoliciesIndexRouteImport.update({
  id: '/policies/',
  path: '/policies/',
  getParentRoute: () => AppLeaveRouteRoute,
} as any)
const AppLeaveRequestsPendingRoute = AppLeaveRequestsPendingRouteImport.update({
  id: '/requests/pending',
  path: '/requests/pending',
  getParentRoute: () => AppLeaveRouteRoute,
} as any)
const AppLeaveRequestsNewRoute = AppLeaveRequestsNewRouteImport.update({
  id: '/requests/new',
  path: '/requests/new',
  getParentRoute: () => AppLeaveRouteRoute,
} as any)
const AppLeavePoliciesNewRoute = AppLeavePoliciesNewRouteImport.update({
  id: '/policies/new',
  path: '/policies/new',
  getParentRoute: () => AppLeaveRouteRoute,
} as any)
const AppLeavePoliciesIdRoute = AppLeavePoliciesIdRouteImport.update({
  id: '/policies/$id',
  path: '/policies/$id',
  getParentRoute: () => AppLeaveRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/attendance': typeof AppAttendanceRouteRouteWithChildren
  '/claims': typeof AppClaimsRouteRouteWithChildren
  '/feature-disabled': typeof AppFeatureDisabledRouteRoute
  '/leave': typeof AppLeaveRouteRouteWithChildren
  '/overview': typeof AppOverviewRouteRoute
  '/people': typeof AppPeopleRouteRouteWithChildren
  '/reports': typeof AppReportsRouteRoute
  '/settings': typeof AppSettingsRouteRouteWithChildren
  '/tasks': typeof AppTasksRouteRoute
  '/invite': typeof AuthInviteRouteRoute
  '/login': typeof AuthLoginRouteRoute
  '/register': typeof AuthRegisterRouteRoute
  '/setup-org': typeof AuthSetupOrgRouteRoute
  '/attendance/monthly': typeof AppAttendanceMonthlyRouteRoute
  '/people/$id': typeof AppPeopleIdRouteRoute
  '/settings/company': typeof AppSettingsCompanyRouteRoute
  '/settings/members': typeof AppSettingsMembersRouteRoute
  '/claims/new': typeof AppClaimsNewRoute
  '/leave/calendar': typeof AppLeaveCalendarRoute
  '/attendance/': typeof AppAttendanceIndexRoute
  '/claims/': typeof AppClaimsIndexRoute
  '/leave/': typeof AppLeaveIndexRoute
  '/people/': typeof AppPeopleIndexRoute
  '/leave/policies/$id': typeof AppLeavePoliciesIdRoute
  '/leave/policies/new': typeof AppLeavePoliciesNewRoute
  '/leave/requests/new': typeof AppLeaveRequestsNewRoute
  '/leave/requests/pending': typeof AppLeaveRequestsPendingRoute
  '/leave/policies/': typeof AppLeavePoliciesIndexRoute
  '/leave/requests/': typeof AppLeaveRequestsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/feature-disabled': typeof AppFeatureDisabledRouteRoute
  '/overview': typeof AppOverviewRouteRoute
  '/reports': typeof AppReportsRouteRoute
  '/settings': typeof AppSettingsRouteRouteWithChildren
  '/tasks': typeof AppTasksRouteRoute
  '/invite': typeof AuthInviteRouteRoute
  '/login': typeof AuthLoginRouteRoute
  '/register': typeof AuthRegisterRouteRoute
  '/setup-org': typeof AuthSetupOrgRouteRoute
  '/attendance/monthly': typeof AppAttendanceMonthlyRouteRoute
  '/people/$id': typeof AppPeopleIdRouteRoute
  '/settings/company': typeof AppSettingsCompanyRouteRoute
  '/settings/members': typeof AppSettingsMembersRouteRoute
  '/claims/new': typeof AppClaimsNewRoute
  '/leave/calendar': typeof AppLeaveCalendarRoute
  '/attendance': typeof AppAttendanceIndexRoute
  '/claims': typeof AppClaimsIndexRoute
  '/leave': typeof AppLeaveIndexRoute
  '/people': typeof AppPeopleIndexRoute
  '/leave/policies/$id': typeof AppLeavePoliciesIdRoute
  '/leave/policies/new': typeof AppLeavePoliciesNewRoute
  '/leave/requests/new': typeof AppLeaveRequestsNewRoute
  '/leave/requests/pending': typeof AppLeaveRequestsPendingRoute
  '/leave/policies': typeof AppLeavePoliciesIndexRoute
  '/leave/requests': typeof AppLeaveRequestsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_app/attendance': typeof AppAttendanceRouteRouteWithChildren
  '/_app/claims': typeof AppClaimsRouteRouteWithChildren
  '/_app/feature-disabled': typeof AppFeatureDisabledRouteRoute
  '/_app/leave': typeof AppLeaveRouteRouteWithChildren
  '/_app/overview': typeof AppOverviewRouteRoute
  '/_app/people': typeof AppPeopleRouteRouteWithChildren
  '/_app/reports': typeof AppReportsRouteRoute
  '/_app/settings': typeof AppSettingsRouteRouteWithChildren
  '/_app/tasks': typeof AppTasksRouteRoute
  '/_auth/invite': typeof AuthInviteRouteRoute
  '/_auth/login': typeof AuthLoginRouteRoute
  '/_auth/register': typeof AuthRegisterRouteRoute
  '/_auth/setup-org': typeof AuthSetupOrgRouteRoute
  '/_app/attendance/monthly': typeof AppAttendanceMonthlyRouteRoute
  '/_app/people/$id': typeof AppPeopleIdRouteRoute
  '/_app/settings/company': typeof AppSettingsCompanyRouteRoute
  '/_app/settings/members': typeof AppSettingsMembersRouteRoute
  '/_app/claims/new': typeof AppClaimsNewRoute
  '/_app/leave/calendar': typeof AppLeaveCalendarRoute
  '/_app/attendance/': typeof AppAttendanceIndexRoute
  '/_app/claims/': typeof AppClaimsIndexRoute
  '/_app/leave/': typeof AppLeaveIndexRoute
  '/_app/people/': typeof AppPeopleIndexRoute
  '/_app/leave/policies/$id': typeof AppLeavePoliciesIdRoute
  '/_app/leave/policies/new': typeof AppLeavePoliciesNewRoute
  '/_app/leave/requests/new': typeof AppLeaveRequestsNewRoute
  '/_app/leave/requests/pending': typeof AppLeaveRequestsPendingRoute
  '/_app/leave/policies/': typeof AppLeavePoliciesIndexRoute
  '/_app/leave/requests/': typeof AppLeaveRequestsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/attendance'
    | '/claims'
    | '/feature-disabled'
    | '/leave'
    | '/overview'
    | '/people'
    | '/reports'
    | '/settings'
    | '/tasks'
    | '/invite'
    | '/login'
    | '/register'
    | '/setup-org'
    | '/attendance/monthly'
    | '/people/$id'
    | '/settings/company'
    | '/settings/members'
    | '/claims/new'
    | '/leave/calendar'
    | '/attendance/'
    | '/claims/'
    | '/leave/'
    | '/people/'
    | '/leave/policies/$id'
    | '/leave/policies/new'
    | '/leave/requests/new'
    | '/leave/requests/pending'
    | '/leave/policies/'
    | '/leave/requests/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/feature-disabled'
    | '/overview'
    | '/reports'
    | '/settings'
    | '/tasks'
    | '/invite'
    | '/login'
    | '/register'
    | '/setup-org'
    | '/attendance/monthly'
    | '/people/$id'
    | '/settings/company'
    | '/settings/members'
    | '/claims/new'
    | '/leave/calendar'
    | '/attendance'
    | '/claims'
    | '/leave'
    | '/people'
    | '/leave/policies/$id'
    | '/leave/policies/new'
    | '/leave/requests/new'
    | '/leave/requests/pending'
    | '/leave/policies'
    | '/leave/requests'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/_app/attendance'
    | '/_app/claims'
    | '/_app/feature-disabled'
    | '/_app/leave'
    | '/_app/overview'
    | '/_app/people'
    | '/_app/reports'
    | '/_app/settings'
    | '/_app/tasks'
    | '/_auth/invite'
    | '/_auth/login'
    | '/_auth/register'
    | '/_auth/setup-org'
    | '/_app/attendance/monthly'
    | '/_app/people/$id'
    | '/_app/settings/company'
    | '/_app/settings/members'
    | '/_app/claims/new'
    | '/_app/leave/calendar'
    | '/_app/attendance/'
    | '/_app/claims/'
    | '/_app/leave/'
    | '/_app/people/'
    | '/_app/leave/policies/$id'
    | '/_app/leave/policies/new'
    | '/_app/leave/requests/new'
    | '/_app/leave/requests/pending'
    | '/_app/leave/policies/'
    | '/_app/leave/requests/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/setup-org': {
      id: '/_auth/setup-org'
      path: '/setup-org'
      fullPath: '/setup-org'
      preLoaderRoute: typeof AuthSetupOrgRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/invite': {
      id: '/_auth/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof AuthInviteRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_app/tasks': {
      id: '/_app/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AppTasksRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/people': {
      id: '/_app/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof AppPeopleRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/overview': {
      id: '/_app/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof AppOverviewRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/leave': {
      id: '/_app/leave'
      path: '/leave'
      fullPath: '/leave'
      preLoaderRoute: typeof AppLeaveRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/feature-disabled': {
      id: '/_app/feature-disabled'
      path: '/feature-disabled'
      fullPath: '/feature-disabled'
      preLoaderRoute: typeof AppFeatureDisabledRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/claims': {
      id: '/_app/claims'
      path: '/claims'
      fullPath: '/claims'
      preLoaderRoute: typeof AppClaimsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/attendance': {
      id: '/_app/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AppAttendanceRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/people/': {
      id: '/_app/people/'
      path: '/'
      fullPath: '/people/'
      preLoaderRoute: typeof AppPeopleIndexRouteImport
      parentRoute: typeof AppPeopleRouteRoute
    }
    '/_app/leave/': {
      id: '/_app/leave/'
      path: '/'
      fullPath: '/leave/'
      preLoaderRoute: typeof AppLeaveIndexRouteImport
      parentRoute: typeof AppLeaveRouteRoute
    }
    '/_app/claims/': {
      id: '/_app/claims/'
      path: '/'
      fullPath: '/claims/'
      preLoaderRoute: typeof AppClaimsIndexRouteImport
      parentRoute: typeof AppClaimsRouteRoute
    }
    '/_app/attendance/': {
      id: '/_app/attendance/'
      path: '/'
      fullPath: '/attendance/'
      preLoaderRoute: typeof AppAttendanceIndexRouteImport
      parentRoute: typeof AppAttendanceRouteRoute
    }
    '/_app/leave/calendar': {
      id: '/_app/leave/calendar'
      path: '/calendar'
      fullPath: '/leave/calendar'
      preLoaderRoute: typeof AppLeaveCalendarRouteImport
      parentRoute: typeof AppLeaveRouteRoute
    }
    '/_app/claims/new': {
      id: '/_app/claims/new'
      path: '/new'
      fullPath: '/claims/new'
      preLoaderRoute: typeof AppClaimsNewRouteImport
      parentRoute: typeof AppClaimsRouteRoute
    }
    '/_app/settings/members': {
      id: '/_app/settings/members'
      path: '/members'
      fullPath: '/settings/members'
      preLoaderRoute: typeof AppSettingsMembersRouteRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/settings/company': {
      id: '/_app/settings/company'
      path: '/company'
      fullPath: '/settings/company'
      preLoaderRoute: typeof AppSettingsCompanyRouteRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/people/$id': {
      id: '/_app/people/$id'
      path: '/$id'
      fullPath: '/people/$id'
      preLoaderRoute: typeof AppPeopleIdRouteRouteImport
      parentRoute: typeof AppPeopleRouteRoute
    }
    '/_app/attendance/monthly': {
      id: '/_app/attendance/monthly'
      path: '/monthly'
      fullPath: '/attendance/monthly'
      preLoaderRoute: typeof AppAttendanceMonthlyRouteRouteImport
      parentRoute: typeof AppAttendanceRouteRoute
    }
    '/_app/leave/requests/': {
      id: '/_app/leave/requests/'
      path: '/requests'
      fullPath: '/leave/requests/'
      preLoaderRoute: typeof AppLeaveRequestsIndexRouteImport
      parentRoute: typeof AppLeaveRouteRoute
    }
    '/_app/leave/policies/': {
      id: '/_app/leave/policies/'
      path: '/policies'
      fullPath: '/leave/policies/'
      preLoaderRoute: typeof AppLeavePoliciesIndexRouteImport
      parentRoute: typeof AppLeaveRouteRoute
    }
    '/_app/leave/requests/pending': {
      id: '/_app/leave/requests/pending'
      path: '/requests/pending'
      fullPath: '/leave/requests/pending'
      preLoaderRoute: typeof AppLeaveRequestsPendingRouteImport
      parentRoute: typeof AppLeaveRouteRoute
    }
    '/_app/leave/requests/new': {
      id: '/_app/leave/requests/new'
      path: '/requests/new'
      fullPath: '/leave/requests/new'
      preLoaderRoute: typeof AppLeaveRequestsNewRouteImport
      parentRoute: typeof AppLeaveRouteRoute
    }
    '/_app/leave/policies/new': {
      id: '/_app/leave/policies/new'
      path: '/policies/new'
      fullPath: '/leave/policies/new'
      preLoaderRoute: typeof AppLeavePoliciesNewRouteImport
      parentRoute: typeof AppLeaveRouteRoute
    }
    '/_app/leave/policies/$id': {
      id: '/_app/leave/policies/$id'
      path: '/policies/$id'
      fullPath: '/leave/policies/$id'
      preLoaderRoute: typeof AppLeavePoliciesIdRouteImport
      parentRoute: typeof AppLeaveRouteRoute
    }
  }
}

interface AppAttendanceRouteRouteChildren {
  AppAttendanceMonthlyRouteRoute: typeof AppAttendanceMonthlyRouteRoute
  AppAttendanceIndexRoute: typeof AppAttendanceIndexRoute
}

const AppAttendanceRouteRouteChildren: AppAttendanceRouteRouteChildren = {
  AppAttendanceMonthlyRouteRoute: AppAttendanceMonthlyRouteRoute,
  AppAttendanceIndexRoute: AppAttendanceIndexRoute,
}

const AppAttendanceRouteRouteWithChildren =
  AppAttendanceRouteRoute._addFileChildren(AppAttendanceRouteRouteChildren)

interface AppClaimsRouteRouteChildren {
  AppClaimsNewRoute: typeof AppClaimsNewRoute
  AppClaimsIndexRoute: typeof AppClaimsIndexRoute
}

const AppClaimsRouteRouteChildren: AppClaimsRouteRouteChildren = {
  AppClaimsNewRoute: AppClaimsNewRoute,
  AppClaimsIndexRoute: AppClaimsIndexRoute,
}

const AppClaimsRouteRouteWithChildren = AppClaimsRouteRoute._addFileChildren(
  AppClaimsRouteRouteChildren,
)

interface AppLeaveRouteRouteChildren {
  AppLeaveCalendarRoute: typeof AppLeaveCalendarRoute
  AppLeaveIndexRoute: typeof AppLeaveIndexRoute
  AppLeavePoliciesIdRoute: typeof AppLeavePoliciesIdRoute
  AppLeavePoliciesNewRoute: typeof AppLeavePoliciesNewRoute
  AppLeaveRequestsNewRoute: typeof AppLeaveRequestsNewRoute
  AppLeaveRequestsPendingRoute: typeof AppLeaveRequestsPendingRoute
  AppLeavePoliciesIndexRoute: typeof AppLeavePoliciesIndexRoute
  AppLeaveRequestsIndexRoute: typeof AppLeaveRequestsIndexRoute
}

const AppLeaveRouteRouteChildren: AppLeaveRouteRouteChildren = {
  AppLeaveCalendarRoute: AppLeaveCalendarRoute,
  AppLeaveIndexRoute: AppLeaveIndexRoute,
  AppLeavePoliciesIdRoute: AppLeavePoliciesIdRoute,
  AppLeavePoliciesNewRoute: AppLeavePoliciesNewRoute,
  AppLeaveRequestsNewRoute: AppLeaveRequestsNewRoute,
  AppLeaveRequestsPendingRoute: AppLeaveRequestsPendingRoute,
  AppLeavePoliciesIndexRoute: AppLeavePoliciesIndexRoute,
  AppLeaveRequestsIndexRoute: AppLeaveRequestsIndexRoute,
}

const AppLeaveRouteRouteWithChildren = AppLeaveRouteRoute._addFileChildren(
  AppLeaveRouteRouteChildren,
)

interface AppPeopleRouteRouteChildren {
  AppPeopleIdRouteRoute: typeof AppPeopleIdRouteRoute
  AppPeopleIndexRoute: typeof AppPeopleIndexRoute
}

const AppPeopleRouteRouteChildren: AppPeopleRouteRouteChildren = {
  AppPeopleIdRouteRoute: AppPeopleIdRouteRoute,
  AppPeopleIndexRoute: AppPeopleIndexRoute,
}

const AppPeopleRouteRouteWithChildren = AppPeopleRouteRoute._addFileChildren(
  AppPeopleRouteRouteChildren,
)

interface AppSettingsRouteRouteChildren {
  AppSettingsCompanyRouteRoute: typeof AppSettingsCompanyRouteRoute
  AppSettingsMembersRouteRoute: typeof AppSettingsMembersRouteRoute
}

const AppSettingsRouteRouteChildren: AppSettingsRouteRouteChildren = {
  AppSettingsCompanyRouteRoute: AppSettingsCompanyRouteRoute,
  AppSettingsMembersRouteRoute: AppSettingsMembersRouteRoute,
}

const AppSettingsRouteRouteWithChildren =
  AppSettingsRouteRoute._addFileChildren(AppSettingsRouteRouteChildren)

interface AppRouteRouteChildren {
  AppAttendanceRouteRoute: typeof AppAttendanceRouteRouteWithChildren
  AppClaimsRouteRoute: typeof AppClaimsRouteRouteWithChildren
  AppFeatureDisabledRouteRoute: typeof AppFeatureDisabledRouteRoute
  AppLeaveRouteRoute: typeof AppLeaveRouteRouteWithChildren
  AppOverviewRouteRoute: typeof AppOverviewRouteRoute
  AppPeopleRouteRoute: typeof AppPeopleRouteRouteWithChildren
  AppReportsRouteRoute: typeof AppReportsRouteRoute
  AppSettingsRouteRoute: typeof AppSettingsRouteRouteWithChildren
  AppTasksRouteRoute: typeof AppTasksRouteRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAttendanceRouteRoute: AppAttendanceRouteRouteWithChildren,
  AppClaimsRouteRoute: AppClaimsRouteRouteWithChildren,
  AppFeatureDisabledRouteRoute: AppFeatureDisabledRouteRoute,
  AppLeaveRouteRoute: AppLeaveRouteRouteWithChildren,
  AppOverviewRouteRoute: AppOverviewRouteRoute,
  AppPeopleRouteRoute: AppPeopleRouteRouteWithChildren,
  AppReportsRouteRoute: AppReportsRouteRoute,
  AppSettingsRouteRoute: AppSettingsRouteRouteWithChildren,
  AppTasksRouteRoute: AppTasksRouteRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthInviteRouteRoute: typeof AuthInviteRouteRoute
  AuthLoginRouteRoute: typeof AuthLoginRouteRoute
  AuthRegisterRouteRoute: typeof AuthRegisterRouteRoute
  AuthSetupOrgRouteRoute: typeof AuthSetupOrgRouteRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthInviteRouteRoute: AuthInviteRouteRoute,
  AuthLoginRouteRoute: AuthLoginRouteRoute,
  AuthRegisterRouteRoute: AuthRegisterRouteRoute,
  AuthSetupOrgRouteRoute: AuthSetupOrgRouteRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
