package main

import (
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/swaggo/swag"
)

// registerDocsRoutes mounts two endpoints:
//
//	GET /docs            → Scalar UI (modern API explorer)
//	GET /docs/openapi.json → raw OpenAPI 2.0 spec generated by swag
func registerDocsRoutes(r *gin.Engine) {
	r.GET("/docs", serveScalarUI)
	r.GET("/docs/openapi.json", serveOpenAPISpec)
}

func serveOpenAPISpec(c *gin.Context) {
	doc, err := swag.ReadDoc()
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": "spec unavailable"})
		return
	}
	c.Header("Content-Type", "application/json; charset=utf-8")
	c.String(http.StatusOK, doc)
}

func serveScalarUI(c *gin.Context) {
	c.Header("Content-Type", "text/html; charset=utf-8")
	c.String(http.StatusOK, scalarHTML)
}

const scalarHTML = `<!doctype html>
<html>
  <head>
    <title>Workived API Reference</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <style>body { margin: 0; }</style>
  </head>
  <body>
    <script
      id="api-reference"
      data-url="/docs/openapi.json"
      data-configuration='{"theme":"purple","layout":"modern"}'></script>
    <script src="https://cdn.jsdelivr.net/npm/@scalar/api-reference"></script>
  </body>
</html>`
